config/routes.rb
Resetme::Application.routes.draw do
  resources :sites

  post 'sites/:id/reset' => 'sites#reset', as: :reset
  
  get "sites/index"

  root 'sites#index'

end

app/models/site.rb
class Site < ActiveRecord::Base
  default_scope order('reset_at ASC')

  def is_password_old?
    reset_at < DateTime.now - 1.months
  end

  def reset_timer!
    update(reset_at: DateTime.now)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  http_basic_authenticate_with name: ENV['RESETME_USER'], password: ENV['RESETME_PASSWORD']
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :set_site, only: [:show, :edit, :update, :destroy, :reset]

  # GET /sites
  # GET /sites.json
  def index
    @sites = Site.all
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
  end

  # GET /sites/new
  def new
    @site = Site.new
  end

  # GET /sites/1/edit
  def edit
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = Site.new(site_params)
    @site.reset_at = DateTime.now
    respond_to do |format|
      if @site.save
        format.html { redirect_to @site, notice: 'Site was successfully created.' }
        format.json { render action: 'show', status: :created, location: @site }
      else
        format.html { render action: 'new' }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sites/1
  # PATCH/PUT /sites/1.json
  def update
    respond_to do |format|
      if @site.update(site_params)
        format.html { redirect_to @site, notice: 'Site was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site.destroy
    respond_to do |format|
      format.html { redirect_to sites_url }
      format.json { head :no_content }
    end
  end

  def reset
    @site.reset_timer!
    respond_to do |format|
      format.html { redirect_to sites_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site
      @site = Site.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_params
      params.require(:site).permit(:url, :name, :username, :logo_url)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Resetme</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sites/_form.html.erb
<%= form_for(@site) do |f| %>
  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% @site.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :logo_url %><br>
    <%= f.text_field :logo_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sites/edit.html.erb
<h1>Editing site</h1>

<%= render 'form' %>

<%= link_to 'Show', @site %> |
<%= link_to 'Back', sites_path %>

app/views/sites/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <h1>RESET ME</h1>
    </div>
    <div class="col-md-8" style="text-align:right">
      <%= link_to raw('<i class="glyphicon glyphicon-plus"></i>'), new_site_path, :class => 'btn btn-success btn-circle btn-lg' %>
      <button type="button" class="btn btn-primary btn-circle btn-lg" onclick="javascript:alert('no funca')"><i class="glyphicon glyphicon-list"></i></button>
      <button type="button" class="btn btn-default btn-circle btn-lg" onclick="javascript:alert('no funca')"><i class="glyphicon glyphicon-log-out"></i></button>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <% @sites.each do |site| %>
      <%
          color = ''
          label = ''

          if site.reset_at < DateTime.now - 2.months
            color = 'offer-danger'
            label = 'bad'
          elsif site.reset_at < DateTime.now - 1.months
            color = 'offer-warning'
            label = 'warn'
          else
            color = 'offer-success'
            label = 'good'
          end
      %>
      <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
        <div class="offer <%= color %>">
          <div class="shape">
            <div class="shape-text">
              <%= label %>
            </div>
          </div>
          <div class="offer-content">
            <h3 class="lead">
              <img src="<%= site.logo_url%>" alt="<%= site.name%>" class="img-circle"> 
              <%= site.name.titleize %>
            </h3>
            <p>
              <strong>username:</strong><em> <%= site.username %></em><br />
              <strong>age:</strong><em> <%= time_ago_in_words(site.reset_at.to_time) %></em>
            </p>
            <p class="options">
              <a href="<%= site.url %>" target="_blank" class="btn btn-primary btn-lg btn-block">Change Password</a>
            </p>
            <p class="options">
              <%= link_to 'Show', site, :class => "btn btn-xs" %>
              <%= link_to 'Edit', edit_site_path(site), :class => "btn btn-xs" %>
              <%= link_to 'Destroy', site, method: :delete, data: { confirm: 'Are you sure?' }, 
                          :class => "btn btn-xs" %>
              <%= link_to 'Reset', reset_url(id: site.id), method: 'post', data: { confirm: 'Are you sure?' }, 
                          :class => "btn btn-xs" %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<br>

app/views/sites/new.html.erb
<h1>New site</h1>

<%= render 'form' %>

<%= link_to 'Back', sites_path %>

app/views/sites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @site.url %>
</p>

<p>
  <strong>Name:</strong>
  <%= @site.name %>
</p>

<p>
  <strong>Username:</strong>
  <%= @site.username %>
</p>


<p>
  <strong>Logo Url:</strong>
  <%= @site.logo_url %>
</p>

<p>
  <strong>Age</strong>
  <%= time_ago_in_words(@site.reset_at.to_time) %>
</p>

<%= link_to 'Edit', edit_site_path(@site) %> |
<%= link_to 'Back', sites_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>